name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Path: LogPro.sln
      Test_Project_Path: src\LogPro.Tests\LogPro.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path --configuration $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build application
      run: dotnet build $env:Solution_Path --configuration $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LogPro-${{ matrix.configuration }}
        path: src\LogPro.App\bin\${{ matrix.configuration }}\net8.0-windows\